export const SEED_PRODUCTS = [
  {
    name: 'Oud Noir Absolu',
    brand: 'Lumière Parfums',
    description: 'A rich and mysterious oud fragrance that evokes the ancient spice routes of the East. Deep, smoky, and intoxicating with a warm amber drydown that lingers for hours.',
    price: 320,
    originalPrice: 380,
    category: 'Men',
    sizes: [
      { ml: 50, price: 220 },
      { ml: 100, price: 320 },
      { ml: 200, price: 480 },
    ],
    images: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&q=80',
      'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=600&q=80',
    ],
    notes: {
      top: ['Saffron', 'Black Pepper', 'Bergamot'],
      heart: ['Oud Wood', 'Rose', 'Incense'],
      base: ['Amber', 'Musk', 'Sandalwood'],
    },
    rating: 4.9,
    reviewCount: 248,
    stock: 45,
    isFeatured: true,
    isBestseller: false,
  },
  {
    name: 'Rose Éternelle',
    brand: 'Lumière Parfums',
    description: 'A timeless bouquet of the world\'s finest roses — Bulgarian, Turkish, and Taif — elevated by delicate green notes and a sensuous base of white musk and peach.',
    price: 280,
    category: 'Women',
    sizes: [
      { ml: 30, price: 180 },
      { ml: 75, price: 280 },
      { ml: 150, price: 420 },
    ],
    images: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=80',
      'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80',
    ],
    notes: {
      top: ['Bulgarian Rose', 'Green Leaves', 'Lychee'],
      heart: ['Turkish Rose', 'Taif Rose', 'Jasmine'],
      base: ['White Musk', 'Peach', 'Cedarwood'],
    },
    rating: 4.8,
    reviewCount: 312,
    stock: 60,
    isFeatured: true,
    isBestseller: true,
  },
  {
    name: 'Vetiver Impérial',
    brand: 'Lumière Parfums',
    description: 'Earthy and sophisticated, this vetiver-forward composition is the quintessential modern gentleman\'s fragrance. Clean, woody, and effortlessly refined.',
    price: 240,
    category: 'Men',
    sizes: [
      { ml: 50, price: 160 },
      { ml: 100, price: 240 },
    ],
    images: [
      'https://images.unsplash.com/photo-1590736969596-bde1c3aad1e0?w=600&q=80',
      'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=80',
    ],
    notes: {
      top: ['Grapefruit', 'Cardamom', 'Violet Leaf'],
      heart: ['Vetiver', 'Geranium', 'Clary Sage'],
      base: ['Oakmoss', 'Tobacco', 'Benzoin'],
    },
    rating: 4.7,
    reviewCount: 189,
    stock: 80,
    isFeatured: false,
    isBestseller: true,
  },
  {
    name: 'Iris Céleste',
    brand: 'Lumière Parfums',
    description: 'A powdery, ethereal iris composition that captures the essence of Parisian chic. Luminous, airy, and hauntingly beautiful on the skin.',
    price: 310,
    category: 'Women',
    sizes: [
      { ml: 30, price: 200 },
      { ml: 75, price: 310 },
      { ml: 150, price: 460 },
    ],
    images: [
      'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=80',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    ],
    notes: {
      top: ['Aldehydes', 'Mandarin', 'Pink Pepper'],
      heart: ['Iris', 'Orris Root', 'Violet'],
      base: ['Cashmere Wood', 'White Musk', 'Tonka Bean'],
    },
    rating: 4.8,
    reviewCount: 276,
    stock: 35,
    isFeatured: true,
    isBestseller: false,
  },
  {
    name: 'Ambre Sauvage',
    brand: 'Lumière Parfums',
    description: 'Bold and untamed, Ambre Sauvage is a golden amber masterpiece with wild, animalic undertones. Commanding, sensual, and impossible to ignore.',
    price: 180,
    originalPrice: 220,
    category: 'Unisex',
    sizes: [
      { ml: 50, price: 120 },
      { ml: 100, price: 180 },
    ],
    images: [
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80',
    ],
    notes: {
      top: ['Citrus', 'Bergamot', 'Pepper'],
      heart: ['Labdanum', 'Ciste', 'Cinnamon'],
      base: ['Amber', 'Civet', 'Vanilla'],
    },
    rating: 4.6,
    reviewCount: 143,
    stock: 90,
    isFeatured: false,
    isBestseller: true,
  },
  {
    name: 'Nuit de Jasmin',
    brand: 'Lumière Parfums',
    description: 'A nocturnal floral that blooms after midnight. White jasmine at its most intoxicating, wrapped in warm skin notes and a trail of soft musk.',
    price: 260,
    category: 'Women',
    sizes: [
      { ml: 30, price: 170 },
      { ml: 75, price: 260 },
    ],
    images: [
      'https://images.unsplash.com/photo-1595535873420-a599195b3f4a?w=600&q=80',
      'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    ],
    notes: {
      top: ['Neroli', 'Green Tea', 'Peach Blossom'],
      heart: ['Jasmine Sambac', 'Tuberose', 'Ylang-Ylang'],
      base: ['Skin Musk', 'Sandalwood', 'Vetiver'],
    },
    rating: 4.7,
    reviewCount: 198,
    stock: 55,
    isFeatured: false,
    isBestseller: false,
  },
  {
    name: 'Bois de Cachemire',
    brand: 'Lumière Parfums',
    description: 'Cashmere wood meets warm spice in this unisex luxury offering. Velvety, cocooning, and profoundly intimate — like a cashmere sweater on a cold winter evening.',
    price: 200,
    category: 'Unisex',
    sizes: [
      { ml: 50, price: 130 },
      { ml: 100, price: 200 },
      { ml: 200, price: 300 },
    ],
    images: [
      'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
      'https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?w=600&q=80',
    ],
    notes: {
      top: ['Nutmeg', 'Cardamom', 'Clove'],
      heart: ['Cashmere Wood', 'Rose', 'Leather'],
      base: ['Musk', 'Vanilla', 'Patchouli'],
    },
    rating: 4.5,
    reviewCount: 167,
    stock: 70,
    isFeatured: false,
    isBestseller: false,
  },
  {
    name: 'Tabac Royal',
    brand: 'Lumière Parfums',
    description: 'A sophisticated tobacco leather fougère that pays homage to classic masculine perfumery. Dry, elegant, and powerfully charismatic.',
    price: 290,
    category: 'Men',
    sizes: [
      { ml: 50, price: 190 },
      { ml: 100, price: 290 },
    ],
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
      'https://images.unsplash.com/photo-1552168324-d612d77725e3?w=600&q=80',
    ],
    notes: {
      top: ['Lavender', 'Bergamot', 'Elemi'],
      heart: ['Tobacco Leaf', 'Leather', 'Geranium'],
      base: ['Oakmoss', 'Labdanum', 'Cedarwood'],
    },
    rating: 4.9,
    reviewCount: 221,
    stock: 40,
    isFeatured: false,
    isBestseller: true,
  },
  {
    name: 'Sillage d\'Or',
    brand: 'Lumière Parfums',
    description: 'Leave a trail of liquid gold wherever you go. This radiant chypre-floral opens with brilliant citrus and blossoms into a rich floral heart above a mossy, resinous base.',
    price: 340,
    category: 'Women',
    sizes: [
      { ml: 30, price: 220 },
      { ml: 75, price: 340 },
      { ml: 150, price: 500 },
    ],
    images: [
      'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&q=80',
      'https://images.unsplash.com/photo-1519415387722-a1c3bbef716c?w=600&q=80',
    ],
    notes: {
      top: ['Bergamot', 'Neroli', 'Aldehydes'],
      heart: ['Jasmine', 'Rose', 'Orris'],
      base: ['Oakmoss', 'Amber', 'Civet'],
    },
    rating: 4.8,
    reviewCount: 295,
    stock: 30,
    isFeatured: false,
    isBestseller: false,
  },
  {
    name: 'Cèdre Blanc',
    brand: 'Lumière Parfums',
    description: 'A clean, minimalist cedar fragrance for those who appreciate understated luxury. Fresh, airy, and endlessly wearable — the perfect skin-close scent.',
    price: 160,
    originalPrice: 190,
    category: 'Unisex',
    sizes: [
      { ml: 50, price: 110 },
      { ml: 100, price: 160 },
    ],
    images: [
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80',
      'https://images.unsplash.com/photo-1575401011546-24c1c44ddfac?w=600&q=80',
    ],
    notes: {
      top: ['Green Apple', 'Lime', 'Watery Accord'],
      heart: ['White Cedar', 'Aquatic Notes', 'Muguet'],
      base: ['White Musk', 'Driftwood', 'Ambergris'],
    },
    rating: 4.4,
    reviewCount: 134,
    stock: 100,
    isFeatured: false,
    isBestseller: false,
  },
  {
    name: 'Patchouli Mystique',
    brand: 'Lumière Parfums',
    description: 'Dark and enchanting, this patchouli-centric composition blends vintage glamour with modern sensibility. Dense, magnetic, and wholly original.',
    price: 220,
    category: 'Unisex',
    sizes: [
      { ml: 50, price: 150 },
      { ml: 100, price: 220 },
      { ml: 200, price: 330 },
    ],
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80',
    ],
    notes: {
      top: ['Dark Rum', 'Cardamom', 'Black Currant'],
      heart: ['Patchouli', 'Incense', 'Dark Rose'],
      base: ['Leather', 'Oud', 'Vanilla'],
    },
    rating: 4.6,
    reviewCount: 178,
    stock: 65,
    isFeatured: false,
    isBestseller: false,
  },
  {
    name: 'Musc Précieux',
    brand: 'Lumière Parfums',
    description: 'The ultimate skin fragrance. A masterful blend of the rarest white musks layered over soft florals and a whisper of sandalwood. Intimate, sensual, deeply personal.',
    price: 380,
    category: 'Unisex',
    sizes: [
      { ml: 30, price: 240 },
      { ml: 75, price: 380 },
      { ml: 150, price: 560 },
    ],
    images: [
      'https://images.unsplash.com/photo-1610484826967-09c5720778c7?w=600&q=80',
      'https://images.unsplash.com/photo-1575401011546-24c1c44ddfac?w=600&q=80',
    ],
    notes: {
      top: ['Aldehydes', 'Bergamot', 'Rose Water'],
      heart: ['White Musk', 'Peony', 'Neroli'],
      base: ['Sandalwood', 'Ambrette', 'Cashmeran'],
    },
    rating: 4.9,
    reviewCount: 342,
    stock: 25,
    isFeatured: false,
    isBestseller: false,
  },
];
